version: 2
updates:
    # pnpm dependabot support currently in the works: https://github.com/dependabot/dependabot-core/issues/1736
    # - package-ecosystem: "pnpm"
    #   directory: "/"
    #   schedule:
    #     interval: "daily"

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
