name: Lint and Format
on:
  push:
  pull_request:
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://get.pnpm.io/install.sh | sh
          export PATH=$HOME/.pnpm/bin:$PATH
          pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Format check
        run: pnpm run format:check
